// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RequestCreateUser struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RequestGetUserById struct {
	Id string `path:"id"`
}

type ResponseCreateUser struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type ResponseException struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type ResponseGetUserById struct {
	Code    int                      `json:"code"`
	Message string                   `json:"message"`
	Data    *ResponseGetUserByIdData `json:"data,omitempty"`
}

type ResponseGetUserByIdData struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}
